//Time table data || format: [semester][section][day][period]{"teacherName","subjectCode"}
export let timeTableData = [
    [
        [
            [["Sirsem1secA","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["1Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["2Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["3Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["4Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem1secB","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem1secC","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ]
    ],
    [
        [
            [["Sirsem2secA","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem2secB","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem2secC","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ]
    ],
    [
        [
            [["Sirsem3secA","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem3secB","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem3secC","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ]
    ],
    [
        [
            [["Sirsem4secA","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem4secB","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem4secC","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ]
    ],
    [
        [
            [["Sirsem5secA","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem5secB","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem5secC","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ]
    ],
    [
        [
            [["Sirsem6secA","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem6secB","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem6secC","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ]
    ],
    [
        [
            [["Sirsem7secA","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem7secB","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem7secC","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ]
    ],
    [
        [
            [["Sirsem8secA","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem8secB","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ],
        [
            [["Sirsem8secC","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"]],
            [["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sir","Subject"],["Sirlast","Subject"]]
        ]
    ]
];
